name: Bug Report
description: Report a bug in xcleanup
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: "Thank you for reporting a bug. Please provide enough details to reproduce the issue."
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Short description of the issue.
      placeholder: Describe the problem.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide clear steps to reproduce the issue.
      placeholder: "1. ...\n2. ..."
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected result
      description: What did you expect to happen?
      placeholder: Expected behavior.
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual result
      description: What actually happened?
      placeholder: Actual behavior.
    validations:
      required: true
